// flow-typed signature: c90a60527ea73e15e1d9be8aa252d680
// flow-typed version: <<STUB>>/@types/node_v^10.3.3/flow_v0.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
