// flow-typed signature: 0e96c648d5986123daf22b3a43e02dfd
// flow-typed version: <<STUB>>/url-loader_v^1.x.x/flow_v0.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'url-loader/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-loader/dist/cjs.js' {
  declare module.exports: $Exports<'url-loader/dist/cjs'>;
}
declare module 'url-loader/dist/index.js' {
  declare module.exports: $Exports<'url-loader/dist/index'>;
}
