// flow-typed signature: ddf68972360462cbe5795cfda5d88949
// flow-typed version: <<STUB>>/@reach/router_v^1.x.x/flow_v0.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/router/es/index' {
  declare module.exports: any;
}

declare module '@reach/router/es/lib/history' {
  declare module.exports: any;
}

declare module '@reach/router/es/lib/utils' {
  declare module.exports: any;
}

declare module '@reach/router/lib/history' {
  declare module.exports: any;
}

declare module '@reach/router/lib/utils' {
  declare module.exports: any;
}

declare module '@reach/router/umd/reach-router' {
  declare module.exports: any;
}

declare module '@reach/router/umd/reach-router.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/router/es/index.js' {
  declare module.exports: $Exports<'@reach/router/es/index'>;
}
declare module '@reach/router/es/lib/history.js' {
  declare module.exports: $Exports<'@reach/router/es/lib/history'>;
}
declare module '@reach/router/es/lib/utils.js' {
  declare module.exports: $Exports<'@reach/router/es/lib/utils'>;
}
declare module '@reach/router/index' {
  declare module.exports: $Exports<'@reach/router'>;
}
declare module '@reach/router/index.js' {
  declare module.exports: $Exports<'@reach/router'>;
}
declare module '@reach/router/lib/history.js' {
  declare module.exports: $Exports<'@reach/router/lib/history'>;
}
declare module '@reach/router/lib/utils.js' {
  declare module.exports: $Exports<'@reach/router/lib/utils'>;
}
declare module '@reach/router/umd/reach-router.js' {
  declare module.exports: $Exports<'@reach/router/umd/reach-router'>;
}
declare module '@reach/router/umd/reach-router.min.js' {
  declare module.exports: $Exports<'@reach/router/umd/reach-router.min'>;
}
